import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
import AppSideBar from "@/Components/AppSideBar";



const publicSans = Public_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-public-sans',
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${publicSans.variable} antialiased`}
      >
        <div className="flex h-screen">
            <AppSideBar />
          <main className="flex-1 overflow-auto py-10 px-8">
              {children}
          </main>
        </div>
      </body>
    </html>
  );
}
